//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPagesRazorWithMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public int ID { get; set; }
        public Nullable<int> TweetID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Tweet Tweet { get; set; }
        public virtual tUser tUser { get; set; }
    }
}
